name: Deploy to GitHub Pages

# Run on every push to master
on:
  push:
    branches:
      - master

# Grant the rights needed to push Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Define the jobs for building and deploying the site
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build site
        run: |
          chmod +x ./convert.sh
          ./convert.sh

      - name: Upload _website artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _website

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
